services:
  # Web service for EC-CUBE
  - type: web
    name: ec-cube
    runtime: docker
    dockerfilePath: ./Dockerfile.render
    buildCommand: ./build.sh
    startCommand: ./start.sh
      
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_DEBUG
        value: 0
      - key: ECCUBE_AUTH_MAGIC
        generateValue: true
      - key: ECCUBE_ADMIN_ROUTE
        value: admin
      - key: ECCUBE_LOCALE
        value: ja
      - key: ECCUBE_TIMEZONE
        value: Asia/Tokyo
      - key: DATABASE_URL
        fromDatabase:
          name: ec-cube-db
          property: connectionString
      - key: MAILER_DSN
        value: smtp://localhost:1025
      - key: ECCUBE_FORCE_SSL
        value: true
        
    autoDeploy: false # 手動デプロイに設定
    
databases:
  - name: ec-cube-db
    databaseName: eccube
    user: eccube
    plan: starter # または必要に応じてアップグレード